export const CONSTANTS = {
  GET_LISTS: "GET_LISTS",
  EDIT_LIST: "EDIT_LIST",
  UPDATE_LIST_ORDER: "UPDATE_LIST_ORDER",
  LISTS_ERROR: "LISTS_ERROR",
  GET_CARDS: "GET_CARDS",
  UPDATE_CARD_ORDER: "UPDATE_CARD_ORDER",
  CARDS_ERROR: "CARDS_ERROR",
};
