export const CONSTANTS = {
  GET_LISTS: "GET_LISTS",
  EDIT_LIST: "EDIT_LIST",
  ADD_LIST: "ADD_LIST",
  DEL_LIST: "DEL_LIST",
  UPDATE_LIST_ORDER: "UPDATE_LIST_ORDER",
  LISTS_ERROR: "LISTS_ERROR",
  GET_CARDS: "GET_CARDS",
  EDIT_CARD: "EDIT_CARD",
  ADD_CARD: "ADD_CARD",
  DEL_CARD: "DEL_CARD",
  UPDATE_CARD_ORDER: "UPDATE_CARD_ORDER",
  CARDS_ERROR: "CARDS_ERROR",
};
