export const CONSTANTS = {
  ADD_LIST: "ADD_LIST",
  GET_LISTS: "GET_LISTS",
  LISTS_ERROR: "LISTS_ERROR",
  DEL_LIST: "DEL_LIST",
  EDIT_LIST: "EDIT_LIST",
  ADD_CARD: "ADD_CARD",
  GET_CARDS: "GET_CARDS",
  CARDS_ERROR: "CARDS_ERROR",
};
